import React, { ReactNode } from 'react';
import './globals.css'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type Props = { children: ReactNode };

export default function RootLayout({children}: Props) {
  return (
    <html>
      <body>
          {children}
      </body>
    </html>
  )
}
